apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: remove-temp-files
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up temporary files..."
        rm -rf /tmp/*
